Controls Buttons reposition / Multi-Selection Operation
ktisis-tools/Ktisis pull request #44
Opened 2022-11-23 19:58 UTC by Fia3D

2022-11-23 20:03 UTC, Fayti1703 requested changes
Hate to be so immediately negative to a first-time contributor, but could you:

1. Correct the indentation on new lines
2. Remove the spurious changes on the lines just before the new lines (I'm guessing that's a CRLF/LF difference)
4. Split your changes across multiple commits (One atomic change per commit)

2022-11-24 00:08 UTC, Fia3D commented
![image](https://user-images.githubusercontent.com/103204902/203666517-7669838d-a30e-4c74-b82c-ee8704e93e4f.png)
Last commit allow to remove the white circle (ctrl + click on rotation)

2022-11-24 00:50 UTC, Fayti1703 requested changes
This is looking quite good! I would request one last change before calling this merge-ready:

2022-11-24 00:50 UTC, Fayti1703 commented on Ktisis/Util/EnumFlagExtension.cs
> +		public static bool FlagHas<T>(this System.Enum type, T value) => ((int)(object)type & (int)(object)value) == (int)(object)value;
This already exists as an instance method on `System.Enum` -- namely `HasFlag`. The other methods here are fine, but this one in specific already has a native implementation.

If you could change your calls to that method and then remove this method here, that'd be great.

2022-11-24 01:34 UTC, Fia3D commented
Should be good now

2022-11-24 01:38 UTC, Fayti1703 approved these changes

2022-11-25 01:11 UTC, Fia3D commented
Rebase to make it compatible with new merged titlebar settings

2022-11-25 14:40 UTC, Fayti1703 commented
Minor thing I just noticed: Could you un-hang the braces in your code? i.e.

```diff
- if (ImGui.GetIO().KeyCtrl)
- {
+ if (ImGui.GetIO().KeyCtrl) {
```

2022-11-25 15:31 UTC, merged