Create fr_FR.json
ktisis-tools/Ktisis pull request #75
Opened 2022-12-09 00:31 UTC by Luna664

2022-12-09 07:29 UTC, Fayti1703 commented
Could you convert the file into the same format used by `en_US.json` and `de_DE.json`? It's currently still in the old, legacy format, which won't work on this branch.

(no need to create a new PR, you can just push additional commits onto your fork's branch and they should show up here)

2022-12-10 02:29 UTC, Luna664 commented
Sorry I had checked the old ENGLISH.json file instead of the En_US.json file.

The file is normally converted as it should be now

2022-12-10 09:07 UTC, therealedited requested changes
There are some grammatical errors that need to be fixed and some context related to the tool that needs to be added. Feel free to argue about any requested changes.

2022-12-10 09:07 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +					"ToggleLocalWorld": "Basculer local/monde",
Maybe rajouter `mode` ? This setting should control how the rotation works

2022-12-10 09:07 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"j_f_dlip_a": "Lèvre inferieure A",
```json
"j_f_dlip_a": "Lèvre inférieure A"
```

2022-12-10 09:07 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"body": "Corp",
```json
"body": "Corps",
```

2022-12-10 09:07 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"feet": "Pied",
```json
"feet": "Pieds",
```

2022-12-10 09:07 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"ivcs body": "IVCS Corp",
```json
"ivcs body": "IVCS Corps"
```

2022-12-10 16:24 UTC, Luna664 commented on Ktisis/Locale/i18n/fr_FR.json
> +				"showSpeedMultiplierInputs": "Afficher les entrées du multiplicateur de vitesse"
I didn't manage to translate this well, I'll talk about it around me to help me find a better way to say it

2022-12-10 16:27 UTC, Luna664 commented on Ktisis/Locale/i18n/fr_FR.json
> +					"CircleThroughSiblingLinkModes": "Circle through sibling link modes"
I didn't manage to translate this sentence too, I tried to do my best, but the translation might not fit

2022-12-10 16:28 UTC, Luna664 commented on Ktisis/Locale/i18n/fr_FR.json
> +					"filter": "Fichiers d'images"
I think "Image files" is more correct, but this is my personal opinion, both can be used

2022-12-10 16:30 UTC, Luna664 commented on Ktisis/Locale/i18n/fr_FR.json
> +					"SwitchToTranslate": "Appuyer pour traduire",
I also failed to translate this correctly, I will talk about it to find a correct translation

2022-12-10 16:38 UTC, therealedited requested changes

2022-12-10 16:38 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
>  				"drawLineWhenSelecting": "Tracer des lignes lors de la sélection",
```json
"drawLineWhenSelecting": "Afficher une ligne lors d'une sélection"
```
sound more in-context to me but I'm not exactly sure where the english text is displayed. Same for the one below `Afficher un point lors d'une selection`

2022-12-10 16:38 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> -					"title": "Presser les touches",
I still don't think it's correct. This text displays in the Input tab and basically shows the user what is the key (or shortcut) that they're currently pressing. `Touches enfoncées` ?

2022-12-10 16:38 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"n_ear_a_l": "Boucles d'oreille A Gauche",
`Oreille` takes a "s" if you decide to use `Boucles`

2022-12-10 16:38 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"j_f_ulip_a": "Lèvre supérieur Droite",
`Lèvre` is feminine. So it's `supérieure`

2022-12-10 16:38 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +				"censorNSFW": "Cacher le contenue explicite"
`contenu` and not `contenue`

2022-12-10 16:52 UTC, Luna664 commented on Ktisis/Locale/i18n/fr_FR.json
> +					"SwitchToTranslate": "Appuyer pour traduire",
A translation was finally found by a friend

2022-12-10 17:11 UTC, therealedited requested changes

2022-12-10 17:11 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"__comment": "Utilisation de l'élément null pour signaler 'et al' dans le tableau ci-dessous. Ne faites pas cela pour votre propre localisation.",
By the way, there was no need to translate `__comment` stuff as this is used for translators and will never be displayed in game.

2022-12-10 17:11 UTC, therealedited commented on Ktisis/Locale/i18n/fr_FR.json
> +		"selfName": "French",
`selfName` should be `Français`

2022-12-13 16:48 UTC, Fayti1703 requested changes

2022-12-13 16:48 UTC, Fayti1703 commented on Ktisis/Locale/i18n/fr_FR.json
> +					"tooltip": "Rafraîchit la mémoire de la planche mirage pour les recherches de sets. \NCette mémoire est conservée après un redémarrage.\N Conditions requises:\NL'une de ces fenêtres doit être ou
Lower case `\n` here, please. `\N` is not a valid JSON escape sequence.

2022-12-13 16:48 UTC, Fayti1703 commented on Ktisis/Locale/i18n/fr_FR.json
> +				"__comment": "NOTE : Ceux-la devraient refléter plus clairement la fonctionnalité réelle (dessiner des lignes/points lorsque le *gizmo est actif*)."",
JSON syntax error here.
```suggestion
				"__comment": "NOTE : Ceux-la devraient refléter plus clairement la fonctionnalité réelle (dessiner des lignes/points lorsque le *gizmo est actif*).",
```

2022-12-13 16:48 UTC, Fayti1703 commented on Ktisis/Locale/i18n/fr_FR.json
> +			null
As the comment above states, "Don't [use a null element] for your own localization".

2022-12-18 23:13 UTC, closed without merging